# Analyse de l'ontologie Gene Ontology (GO)

Comparaison des versions **oct. 2025** et **jan. 2026** sur le domaine *DNA repair* (`GO:0006281`).

In [28]:
import sys
from pathlib import Path

import pandas as pd

# Les scripts utilitaires sont dans le même dossier que ce notebook
ANALYSE_DIR = Path().resolve()
sys.path.insert(0, str(ANALYSE_DIR))

from load_ontologies import (
    GO_NS,
    PATH_GO_NEW,
    PATH_GO_OLD,
    get_stats,
    load_ontology,
)

## Section 1 - Exploration générale des deux versions GO

Chargement des deux fichiers OWL et calcul des statistiques globales via `get_stats()`.

> **nb_axiomes** : axiomes logiques (SubClassOf + EquivalentClasses + DisjointWith), aligné avec Protégé.

In [29]:
print("Chargement GO oct. 2025 …")
onto_old = load_ontology(PATH_GO_OLD)

print("Chargement GO jan. 2026 …")
onto_new = load_ontology(PATH_GO_NEW)

stats_old = get_stats(onto_old, "GO_10-25", PATH_GO_OLD)
stats_new = get_stats(onto_new, "GO_01-26", PATH_GO_NEW)

rows = {
    "nb_classes":    [stats_old["nb_classes"],              stats_new["nb_classes"]],
    "nb_proprietes": [stats_old["proprietes"]["total"],     stats_new["proprietes"]["total"]],
    "  obj_props":   [stats_old["proprietes"]["object_properties"],
                      stats_new["proprietes"]["object_properties"]],
    "  data_props":  [stats_old["proprietes"]["data_properties"],
                      stats_new["proprietes"]["data_properties"]],
    "  annot_props": [stats_old["proprietes"]["annotation_properties"],
                      stats_new["proprietes"]["annotation_properties"]],
    "nb_axiomes":    [stats_old["nb_axiomes"],               stats_new["nb_axiomes"]],
    "nb_individus":  [stats_old["nb_individus"],             stats_new["nb_individus"]],
}

df_stats = pd.DataFrame(rows, index=["GO_10-25", "GO_01-26"])
df_stats.index.name = "version"

delta = df_stats.loc["GO_01-26"] - df_stats.loc["GO_10-25"]
df_stats.loc["Δ (01-26 − 10-25)"] = delta

df_stats

Chargement GO oct. 2025 …
Chargement GO jan. 2026 …

,nb_classes,nb_proprietes,obj_props,data_props,annot_props,nb_axiomes,nb_individus
version,,,,,,,
GO_10-25,51842,71,9,0,62,86960,0
GO_01-26,51897,75,9,0,66,84682,0
Δ (01-26 − 10-25),55,4,0,0,4,-2278,0

## Section 2 - Analyse quantitative du domaine DNA repair (`GO:0006281`)

Pour chaque version on calcule :
- **nb_classes_domaine** : nombre de termes dans le sous-arbre `GO:0006281` (hiérarchie **is_a** uniquement)
- **nb_classes_nouvelles** : termes apparus dans la nouvelle version
- **nb_classes_supprimées** : termes absents de la nouvelle version
- **nb_deprecated** : termes marqués `owl:deprecated true`
- **nb_hierarchie_changée** : termes dont les parents `is_a` directs ont changé

> La traversée utilise SPARQL 1.1 (`rdfs:subClassOf*`) sur le world owlready2.
> On compte uniquement la hiérarchie **is_a** (rdfs:subClassOf), pas part_of/regulates.

In [30]:
# DNA REPAIR
DOMAIN_ROOT_ID = "GO:0006281"

# Programmed Death Cell (apoptose)
# 0012501 

# Lipid Metabolism
# 0006629 


def go_id_to_iri(go_id: str) -> str:
    return GO_NS + go_id.replace(":", "_")


def get_descendants(onto, root_go_id: str) -> set:
    """SPARQL 1.1 rdfs:subClassOf* sur le world owlready2 - retourne un ensemble d'IRI (str)."""
    root_iri = go_id_to_iri(root_go_id)
    try:
        q = "SELECT DISTINCT ?sub WHERE { ?sub rdfs:subClassOf* <%s> . FILTER(ISIRI(?sub)) }" % root_iri
        rows = list(onto.world.sparql(q))
        return {str(row[0]) for row in rows}
    except Exception as e:
        print(f"  [WARN] SPARQL descendants échoué pour {root_go_id}: {e}")
        return set()


def count_deprecated(onto, class_iris: set) -> int:
    return sum(
        1 for cls in onto.classes()
        if cls.iri in class_iris and getattr(cls, "deprecated", None)
    )


def get_direct_parents(cls) -> set:
    return {p.iri for p in cls.is_a if getattr(p, "iri", None)}


def count_hierarchy_changes(onto_old, onto_new, iris_common: set) -> int:
    old_idx = {cls.iri: cls for cls in onto_old.classes() if cls.iri in iris_common}
    new_idx = {cls.iri: cls for cls in onto_new.classes() if cls.iri in iris_common}
    return sum(
        1 for iri in iris_common
        if old_idx.get(iri) and new_idx.get(iri)
        and get_direct_parents(old_idx[iri]) != get_direct_parents(new_idx[iri])
    )

In [31]:
print(f"Extraction des descendants de {DOMAIN_ROOT_ID} …")
iris_old = get_descendants(onto_old, DOMAIN_ROOT_ID)
iris_new = get_descendants(onto_new, DOMAIN_ROOT_ID)

iris_added   = iris_new - iris_old
iris_removed = iris_old - iris_new
iris_common  = iris_old & iris_new

print("Comptage des classes dépréciées …")
n_depr_old = count_deprecated(onto_old, iris_old)
n_depr_new = count_deprecated(onto_new, iris_new)

print("Détection des changements de hiérarchie …")
n_hier_changed = count_hierarchy_changes(onto_old, onto_new, iris_common)

results = {
    "nb_classes_domaine":    [len(iris_old),    len(iris_new)],
    "nb_classes_nouvelles":  ["-",              len(iris_added)],
    "nb_classes_supprimées": [len(iris_removed), "-"],
    "nb_deprecated":         [n_depr_old,        n_depr_new],
    "nb_hierarchie_changée": ["-",               n_hier_changed],
}

df_quant = pd.DataFrame(results, index=["GO_10-25", "GO_01-26"])
df_quant.index.name = "version"
df_quant

Extraction des descendants de GO:0006281 …
Comptage des classes dépréciées …
Détection des changements de hiérarchie …

,nb_classes_domaine,nb_classes_nouvelles,nb_classes_supprimées,nb_deprecated,nb_hierarchie_changée
version,,,,,
GO_10-25,44,-,1,0,-
GO_01-26,46,3,-,0,0

## Section 3 - Analyse qualitative

Les 5 termes retenus sont **découverts automatiquement** : on scanne tous les termes communs
du domaine *DNA repair* (`GO:0006281`) pour détecter un changement de définition, de
hiérarchie (`is_a`) ou de relation OBO (`part_of`, `regulates`…).
Si aucun changement n'y est trouvé, le domaine est élargi progressivement vers
`GO:0006259` (*DNA metabolic process*) puis `GO:0006974`
(*cellular response to DNA damage stimulus*).

In [32]:
from typing import Optional, Dict, List, Any
from owlready2 import Restriction

# OBO object-property IDs used in GO axioms
OBO_RELATION_LABELS = {
    # BFO — Basic Formal Ontology 
    "BFO_0000050": "part_of",                  # http://purl.obolibrary.org/obo/BFO_0000050
    "BFO_0000051": "has_part",                 # http://purl.obolibrary.org/obo/BFO_0000051
    # RO — OBO Relations Ontology
    "RO_0002211":  "regulates",                # http://purl.obolibrary.org/obo/RO_0002211
    "RO_0002212":  "negatively_regulates",     # http://purl.obolibrary.org/obo/RO_0002212
    "RO_0002213":  "positively_regulates",     # http://purl.obolibrary.org/obo/RO_0002213
    "RO_0002264":  "acts_upstream_of_or_within",# http://purl.obolibrary.org/obo/RO_0002264
    "RO_0002295":  "results_in_development_of",# http://purl.obolibrary.org/obo/RO_0002295
    "RO_0002296":  "results_in_morphogenesis_of",# http://purl.obolibrary.org/obo/RO_0002296
    "RO_0002297":  "results_in_maturation_of", # http://purl.obolibrary.org/obo/RO_0002297
    "RO_0001000":  "derives_from",             # http://purl.obolibrary.org/obo/RO_0001000
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _go_iri(go_id):
    return GO_NS + go_id.replace(":", "_")

def _iri_to_go(iri):
    local = iri.rsplit("/", 1)[-1]
    return local.replace("_", ":", 1) if local.startswith("GO_") else local

def _get_cls(onto, go_id):
    return onto.search_one(iri=_go_iri(go_id))

def _get_label(onto, go_id):
    cls = _get_cls(onto, go_id)
    if cls is None:
        return go_id
    lbl = getattr(cls, "label", None)
    if lbl:
        return lbl[0] if isinstance(lbl, list) else str(lbl)
    return go_id

def _get_definition(onto, go_id):
    cls = _get_cls(onto, go_id)
    if cls is None:
        return None
    for attr in ("IAO_0000115", "comment"):
        v = getattr(cls, attr, None)
        if v:
            v = v[0] if isinstance(v, list) else v
            if v:
                return str(v)
    return None

def _get_parents(onto, go_id):
    cls = _get_cls(onto, go_id)
    if cls is None:
        return []
    return [p.iri for p in cls.is_a if hasattr(p, "iri") and p.iri]

def _get_relations(onto, go_id):
    cls = _get_cls(onto, go_id)
    if cls is None:
        return {}
    relations = {}
    for axiom in cls.is_a:
        if not isinstance(axiom, Restriction):
            continue
        local = axiom.property.iri.rsplit("/", 1)[-1] if hasattr(axiom.property, "iri") else str(axiom.property)
        lbl = OBO_RELATION_LABELS.get(local, local)
        target = axiom.value
        if target is None or not hasattr(target, "iri"):
            continue
        relations.setdefault(lbl, []).append(_iri_to_go(target.iri))
    return relations

# ---------------------------------------------------------------------------
# Comparaison terme à terme
# ---------------------------------------------------------------------------

def compare_term(onto_old, onto_new, go_id):
    label  = _get_label(onto_new, go_id) or _get_label(onto_old, go_id)
    def_old, def_new = _get_definition(onto_old, go_id), _get_definition(onto_new, go_id)
    par_old, par_new = set(_get_parents(onto_old, go_id)), set(_get_parents(onto_new, go_id))
    rel_old, rel_new = _get_relations(onto_old, go_id), _get_relations(onto_new, go_id)
    pairs_old = {(r, t) for r, ts in rel_old.items() for t in ts}
    pairs_new = {(r, t) for r, ts in rel_new.items() for t in ts}
    return {
        "go_id":              go_id,
        "label":              label,
        "definition_changed": def_old != def_new,
        "definition_old":     def_old,
        "definition_new":     def_new,
        "parents_old":        sorted(_iri_to_go(p) for p in par_old),
        "parents_new":        sorted(_iri_to_go(p) for p in par_new),
        "parents_added":      sorted(_iri_to_go(p) for p in (par_new - par_old)),
        "parents_removed":    sorted(_iri_to_go(p) for p in (par_old - par_new)),
        "relations_old":      rel_old,
        "relations_new":      rel_new,
        "relations_added":    sorted(pairs_new - pairs_old),
        "relations_removed":  sorted(pairs_old - pairs_new),
    }

In [ ]:
# ---------------------------------------------------------------------------
# Découverte automatique des termes ayant changé entre les deux versions GO
# ---------------------------------------------------------------------------
# Domaines explorés progressivement si aucun changement n'est détecté
BROADER_DOMAINS = [
    ("GO:0006281", "DNA repair",                              iris_common),
    ("GO:0006259", "DNA metabolic process",                   None),
    ("GO:0006974", "cellular response to DNA damage stimulus", None),
]

scanothers = False

def _scan_domain_changes(onto_old, onto_new, common_iris):
    """Retourne les résultats compare_term pour les termes GO ayant au
    moins un changement (définition, hiérarchie is_a, ou relation OBO)."""
    results = []
    for iri in sorted(common_iris):
        local = iri.rsplit("/", 1)[-1]
        if not local.startswith("GO_"):
            continue
        go_id = local.replace("_", ":", 1)
        c = compare_term(onto_old, onto_new, go_id)
        if (c["definition_changed"]
                or c["parents_added"] or c["parents_removed"]
                or c["relations_added"] or c["relations_removed"]):
            results.append(c)
    return results

if(scanothers):
    TERM_IDS: List[str] = []
    all_changed: List[Dict[str, Any]] = []
    found_root: Optional[str] = None

    for root_id, root_label, precomputed in BROADER_DOMAINS:
        if precomputed is not None:
            common_set = precomputed
        else:
            print(f"\nÉlargissement → {root_id} ({root_label}) …")
            iris_o = get_descendants(onto_old, root_id)
            iris_n = get_descendants(onto_new, root_id)
            common_set = iris_o & iris_n
            print(f"  {len(common_set)} termes communs")

        print(f"Scan des changements dans {root_id} ({root_label}) …")
        changed = _scan_domain_changes(onto_old, onto_new, common_set)

        if changed:
            print(f"  → {len(changed)} terme(s) modifié(s) :")
            for c in changed[:10]:
                types = []
                if c["definition_changed"]:
                    types.append("définition")
                if c["parents_added"] or c["parents_removed"]:
                    types.append("hiérarchie")
                if c["relations_added"] or c["relations_removed"]:
                    types.append("relations OBO")
                print(f"    • {c['go_id']} — {c['label']} [{', '.join(types)}]")
            if len(changed) > 10:
                print(f"    … et {len(changed) - 10} autre(s).")
            found_root = f"{root_id} ({root_label})"
            all_changed = changed
            # Sélection : on prend jusqu'à 4 termes modifiés ; on préfixe par la racine de domaine si absente
            picked = [c["go_id"] for c in changed[:4]]
            if root_id not in picked:
                picked = [root_id] + picked[:4]
            TERM_IDS = picked[:5]
            break

if not TERM_IDS:
    print("\nAucun terme modifié trouvé dans les domaines explorés.")
    print("Utilisation des termes par défaut (DNA repair).")
    # TERM_IDS = ["GO:0006281", "GO:0006284", "GO:0006289", "GO:0006298", "GO:0006302"]
    TERM_IDS = ["GO:0006281", "GO:0106044", "GO:0010776", "GO:0000286", "GO:0006302"]

print(f"\n{'='*60}")
print("Termes retenus pour l'analyse qualitative")
if found_root:
    print(f"  Domaine source : {found_root}")
print(f"{'='*60}")
for go_id in TERM_IDS:
    lbl = _get_label(onto_new, go_id) or _get_label(onto_old, go_id)
    print(f"  - {go_id} : {lbl}")

# ---------------------------------------------------------------------------
# Résumé tabulaire (une ligne par terme retenu)
# ---------------------------------------------------------------------------
comparisons = [compare_term(onto_old, onto_new, gid) for gid in TERM_IDS]

summary = pd.DataFrame([{
    "go_id":           c["go_id"],
    "label":           c["label"],
    "def_changée":     c["definition_changed"],
    "parents_ajoutés": len(c["parents_added"]),
    "parents_retirés": len(c["parents_removed"]),
    "rel_ajoutées":    len(c["relations_added"]),
    "rel_retirées":    len(c["relations_removed"]),
} for c in comparisons]).set_index("go_id")

summary

Scan des changements dans GO:0006281 (DNA repair) …
  Aucun changement détecté dans ce domaine.

Élargissement → GO:0006259 (DNA metabolic process) …
  233 termes communs
Scan des changements dans GO:0006259 (DNA metabolic process) …
  Aucun changement détecté dans ce domaine.

Élargissement → GO:0006974 (cellular response to DNA damage stimulus) …
  62 termes communs
Scan des changements dans GO:0006974 (cellular response to DNA damage stimulus) …
  Aucun changement détecté dans ce domaine.

Aucun terme modifié trouvé dans les domaines explorés.
Utilisation des termes par défaut (DNA repair).

============================================================
Termes retenus pour l'analyse qualitative
============================================================
  - GO:0006281 : DNA repair
  - GO:0106044 : guanine deglycation
  - GO:0010776 : obsolete meiotic mismatch repair involved in meiotic gene conversion
  - GO:0000286 : L-alanine dehydrogenase (NAD+) activity
  - GO:0006302 : double-strand break repair

,label,def_changée,parents_ajoutés,parents_retirés,rel_ajoutées,rel_retirées
go_id,,,,,,
GO:0006281,DNA repair,False,0,0,0,0
GO:0106044,guanine deglycation,False,1,1,0,0
GO:0010776,obsolete meiotic mismatch repair involved in m...,True,1,1,0,1
GO:0000286,L-alanine dehydrogenase (NAD+) activity,True,1,1,0,0
GO:0006302,double-strand break repair,False,0,0,0,0

In [34]:
from IPython.display import Markdown, display

def _fmt_def(label, text):
    if text is None:
        return f"*{label}* : *(absente)*"
    short = text[:200] + "…" if len(text) > 200 else text
    return f"*{label}* : {short}"

for c in comparisons:
    lines = [f"### {c['go_id']} — {c['label']}", ""]

    # Définition
    lines.append("**Définition**")
    if not c["definition_changed"]:
        lines.append("Inchangée entre les deux versions.")
    else:
        lines.append(_fmt_def("oct. 2025", c["definition_old"]))
        lines.append("")
        lines.append(_fmt_def("jan. 2026", c["definition_new"]))
    lines.append("")

    # Hiérarchie
    lines.append("**Hiérarchie (parents is_a)**")
    if not c["parents_added"] and not c["parents_removed"]:
        lines.append("Aucun changement.")
    else:
        for p in c["parents_added"]:
            lines.append(f"- + `{p}`")
        for p in c["parents_removed"]:
            lines.append(f"- - `{p}`")
    if c["parents_new"]:
        lines.append(f"Parents actuels (jan. 2026) : {', '.join(f'`{p}`' for p in c['parents_new'])}")
    lines.append("")

    # Relations OBO
    lines.append("**Relations OBO (part_of, regulates…)**")
    if not c["relations_added"] and not c["relations_removed"]:
        lines.append("Aucun changement.")
    else:
        for rel, tgt in c["relations_added"]:
            lines.append(f"- + `{rel}` -> `{tgt}`")
        for rel, tgt in c["relations_removed"]:
            lines.append(f"- - `{rel}` -> `{tgt}`")
    if c["relations_new"]:
        lines.append("Relations actuelles (jan. 2026) :")
        for rel, targets in sorted(c["relations_new"].items()):
            lines.append(f"  - `{rel}` : {', '.join(f'`{t}`' for t in targets)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    display(Markdown("\n".join(lines)))

### GO:0006281 — DNA repair

**Définition**
Inchangée entre les deux versions.

**Hiérarchie (parents is_a)**
Aucun changement.
Parents actuels (jan. 2026) : `GO:0006259`, `GO:0006974`

**Relations OBO (part_of, regulates…)**
Aucun changement.

---

### GO:0106044 — guanine deglycation

**Définition**
Inchangée entre les deux versions.

**Hiérarchie (parents is_a)**
- + `GO:0006281`
- - `GO:0009117`
Parents actuels (jan. 2026) : `GO:0006281`

**Relations OBO (part_of, regulates…)**
Aucun changement.

---

### GO:0010776 — obsolete meiotic mismatch repair involved in meiotic gene conversion

**Définition**
*oct. 2025* : A system for the identification and correction of base-base mismatches, small insertion-deletion loops, and regions of heterology that are present in duplex DNA formed with strands from two recombinin…

*jan. 2026* : OBSOLETE. A system for the identification and correction of base-base mismatches, small insertion-deletion loops, and regions of heterology that are present in duplex DNA formed with strands from two …

**Hiérarchie (parents is_a)**
- + `owl#Thing`
- - `GO:0000710`
Parents actuels (jan. 2026) : `owl#Thing`

**Relations OBO (part_of, regulates…)**
- - `part_of` -> `GO:0006311`

---

### GO:0000286 — L-alanine dehydrogenase (NAD+) activity

**Définition**
*oct. 2025* : Catalysis of the reaction: L-alanine + H2O + NAD+ = pyruvate + NH3 + NADH + H+.

*jan. 2026* : Catalysis of the reaction: L-alanine + NAD+ + H2O = pyruvate + NH4+ + NADH + H+.

**Hiérarchie (parents is_a)**
- + `GO:0050018`
- - `GO:0016638`
Parents actuels (jan. 2026) : `GO:0050018`

**Relations OBO (part_of, regulates…)**
Aucun changement.

---

### GO:0006302 — double-strand break repair

**Définition**
Inchangée entre les deux versions.

**Hiérarchie (parents is_a)**
Aucun changement.
Parents actuels (jan. 2026) : `GO:0006281`

**Relations OBO (part_of, regulates…)**
Aucun changement.

---

## Section 4 - Raisonnement OWL avec HermiT

HermiT est lancé sur les deux versions GO pour vérifier la **cohérence globale** de l'ontologie
et identifier les classes incohérentes dans le domaine *DNA repair*.

> Les ontologies `onto_old` / `onto_new` sont déjà chargées en Section 1 et réutilisées ici.
> Le heap JVM est lu depuis `reasoner_config.ini` (`memory_mb`).
> **Attention :** cette cellule peut prendre plusieurs minutes.

In [35]:
import shutil
import time
import owlready2
from owlready2 import OwlReadyInconsistentOntologyError, World
from reasoner_analysis import get_java_malloc, setup_java, run_reasoner

setup_java()

[INFO] Java path     : C:\Program Files\Eclipse Adoptium\jdk-25.0.2.10-hotspot\bin\java.EXE
[INFO] Version Java  : (25, 'openjdk version "25.0.2" 2026-01-20 LTS')
[INFO] Heap Java     : -Xmx4000M

True

In [ ]:
mem_mb = get_java_malloc()

versions = [
    ("GO_10-25", onto_old, iris_old),
    ("GO_01-26", onto_new, iris_new),
]

reasoner_rows = []
for label, onto, dna_iris in versions:
    print(f"\n--- {label} ---")
    r = run_reasoner(onto, "HermiT", onto.world, dna_iris, memory_mb=mem_mb)
    print(f"  Temps              : {r['elapsed_seconds']} s")
    print(f"  Ontologie coherente: {r['ontology_consistent']}")
    if r["error"]:
        print(f"  Erreur             : {r['error'][:200]}")
    print(f"  Inc. totales       : {len(r['inconsistent_classes_total'])}")
    print(f"  Inc. DNA repair    : {len(r['inconsistent_classes_dna_repair'])}")
    reasoner_rows.append({
        "version":            label,
        "temps_s":            r["elapsed_seconds"],
        "coherente":          r["ontology_consistent"],
        "inc_totales":        len(r["inconsistent_classes_total"]),
        "inc_dna_repair":     len(r["inconsistent_classes_dna_repair"]),
        "erreur":             r["error"] or "",
    })

df_reasoner = pd.DataFrame(reasoner_rows).set_index("version")
df_reasoner

--- GO_10-25 ---

* Owlready2 * Running HermiT...
    C:\Program Files\Eclipse Adoptium\jdk-25.0.2.10-hotspot\bin\java.EXE -Xmx4000M -cp c:\Users\vicgo\Desktop\DESS SDIA\Lundi\INF6253 - Web sémantique\Projet2_WebSemantique\Projet2_Ontology_medical\.venv\lib\site-packages\owlready2\hermit;c:\Users\vicgo\Desktop\DESS SDIA\Lundi\INF6253 - Web sémantique\Projet2_WebSemantique\Projet2_Ontology_medical\.venv\lib\site-packages\owlready2\hermit\HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:///C:/Users/vicgo/AppData/Local/Temp/tmpxw8gbi3t
* Owlready2 * HermiT took 103.0732672214508 seconds
* Owlready * Reparenting obo.GO_0034357: {obo.GO_0016020} => {obo.GO_0031090}
* Owlready * Reparenting obo.GO_0099634: {obo.GO_0097060} => {obo.GO_0097060, obo.GO_0031090}
* Owlready * Reparenting obo.GO_0098892: {obo.GO_0098890} => {obo.GO_0031312, obo.GO_0098890}
* Owlready * Reparenting obo.RO_0002212: {owl.ObjectProperty, obo.RO_0002211} => {obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002213: {owl.ObjectProperty, obo.RO_0002211} => {obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002092: {obo.RO_0002093, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002093, owl.TransitiveProperty}
* Owlready * (NB: only changes on entities loaded in Python are shown, other changes are done but not listed)

  Temps              : 110.61 s
  Ontologie coherente: True
  Inc. totales       : 0
  Inc. DNA repair    : 0

--- GO_01-26 ---

* Owlready2 * Running HermiT...
    C:\Program Files\Eclipse Adoptium\jdk-25.0.2.10-hotspot\bin\java.EXE -Xmx4000M -cp c:\Users\vicgo\Desktop\DESS SDIA\Lundi\INF6253 - Web sémantique\Projet2_WebSemantique\Projet2_Ontology_medical\.venv\lib\site-packages\owlready2\hermit;c:\Users\vicgo\Desktop\DESS SDIA\Lundi\INF6253 - Web sémantique\Projet2_WebSemantique\Projet2_Ontology_medical\.venv\lib\site-packages\owlready2\hermit\HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:///C:/Users/vicgo/AppData/Local/Temp/tmp180_73rl
* Owlready2 * HermiT took 96.73351955413818 seconds

  Temps              : 117.42 s
  Ontologie coherente: True
  Inc. totales       : 0
  Inc. DNA repair    : 0

* Owlready * Reparenting obo.GO_0035448: {obo.GO_0019898} => {obo.GO_0031312}
* Owlready * Reparenting obo.GO_0098892: {obo.GO_0098890} => {obo.GO_0098890, obo.GO_0031312}
* Owlready * Reparenting obo.GO_0099634: {obo.GO_0097060} => {obo.GO_0031090, obo.GO_0097060}
* Owlready * Reparenting obo.GO_0060171: {obo.GO_0032589} => {obo.GO_0031090, obo.GO_0032589}
* Owlready * Reparenting obo.GO_0034357: {obo.GO_0016020} => {obo.GO_0031090}
* Owlready * Reparenting obo.RO_0002092: {obo.RO_0002093, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002093, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002212: {owl.ObjectProperty, obo.RO_0002211} => {obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002213: {owl.ObjectProperty, obo.RO_0002211} => {obo.RO_0002211}
* Owlready * (NB: only changes on entities loaded in Python are shown, other changes are done but not listed)

          temps_s  coherente  inc_totales  inc_dna_repair erreur
version
GO_10-25   110.61       True            0               0
GO_01-26   117.42       True            0               0